---

resources:

- name: sample-tile-repo
  type: git
  source:
    paths: [ "sample" ]
    branch: docker
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: tile-generator-repo
  type: git
  source:
    ignore_paths: [ "sample" ]
    branch: docker
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: dockerfile-repo
  type: git
  source:
    paths: [ "ci/Dockerfile", "ci/requirements.txt" ]
    branch: docker
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: ci-docker-image
  type: docker-image
  source:
    repository: guidowb/tile-pipeline2
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: app-docker-image
  type: docker-image
  source:
    repository: guidowb/sample-cf-app2
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: tile-history
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: tile\-history-(?P<version>.*)\.yml
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

jobs:

- name: build-docker
  plan:
  - get: dockerfile-repo
    trigger: true
  - put: ci-docker-image
    params:
      build: dockerfile-repo/ci

- name: build-tile
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ build-docker ]
      trigger: true
    - get: tile-generator-repo
      trigger: true
    - get: sample-tile-repo
      trigger: true
    - get: tile-history
      trigger: false
  - task: build-sample-apps
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: sample-tile-repo
      outputs:
      - name: sample-tile-build
      run:
        path: sample-tile-repo/sample/src/build.sh
        args: [ "sample-tile-build" ]
  - put: app-docker-image
    params:
      build: sample-tile-build/src
  - task: import-app-image
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: app-docker-image
      outputs:
      - name: app-image
      run:
        path: sh
        args: [ "-c", 'ls -l app-docker-image; tar tvf app-docker-image/image']
  # - task: build-sample-tile
  #   config:
  #     platform: linux
  #     image: "docker:///guidowb/tile-pipeline"
  #     inputs:
  #     - name: tile-generator-repo
  #     - name: sample-tile-build
  #     - name: tile-history
  #     outputs:
  #     - name: generated-tile
  #     run:
  #       path: tile-generator-repo/ci/scripts/tile-build.sh
  #       args: [ "sample-tile-build", "tile-history", "generated-tile" ]
