---

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:

- name: tile-generator-repo
  type: git
  source:
    ignore_paths: [ "ci/*-tests" ]
    branch: {{github-branch}}
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: tile-generator-tests
  type: git
  source:
    paths: [ "ci/*-tests", "ci/scripts" ]
    branch: {{github-branch}}
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: base-pipeline-dockerfile-repo
  type: git
  source:
    paths: [ "ci/docker-tile-pipeline" ]
    branch: {{github-branch}}
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: tile-generator-dockerfile-repo
  type: git
  source:
    paths: [ "ci/docker-tile-generator" ]
    branch: {{github-branch}}
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: tile-generator-package
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: tile_generator-(?P<version>.*).tar.gz
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: generated-tile
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: .*-(?P<version>.*)\.pivotal
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: redis-boshrelease
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: redis-(?P<version>.*)\+dev.1.tgz
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: tile-history
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: tile\-history-(?P<version>.*)\.yml
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: base-pipeline-docker-image
  type: docker-image
  source:
    repository: guidowb/base-pipeline
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: tile-generator-docker-image
  type: docker-image
  source:
    repository: guidowb/tile-generator
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: app-docker-image
  type: docker-image
  source:
    repository: guidowb/sample-cf-app
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: pcf-environment
  type: pool
  source:
    uri: git@github.com:cf-platform-eng/pipeline-resource-pool
    branch: master
    pool: pcf
    private_key: {{github-pool-private-key}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-hook}}

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:cf-platform-eng/tile-generator
    branch: version
    file: version
    private_key: {{github-semver-private-key}}

jobs:

- name: build-base-image
  plan:
  - get: base-pipeline-dockerfile-repo
    trigger: true
  - put: base-pipeline-docker-image
    params:
      build: base-pipeline-dockerfile-repo/ci/docker-tile-pipeline

- name: unit-tests
  plan:
  - aggregate:
    - get: base-pipeline-docker-image
      passed: [ build-base-image ]
      trigger: true
    - get: tile-generator-repo
      trigger: true
  - task: run-unit-tests
    image: base-pipeline-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-repo
      run:
        path: tile-generator-repo/ci/scripts/run-unittests.sh
        args: [ "tile-generator-repo/tile_generator" ]
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Unit tests failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: create-dev
  plan:
  - aggregate:
    - get: base-pipeline-docker-image
      passed: [ unit-tests ]
      trigger: true
    - get: tile-generator-repo
      passed: [ unit-tests ]
      trigger: true
  - put: version
    params:
      pre: dev

- name: create-patch
  plan:
  - put: version
    params:
      bump: patch

- name: create-minor
  plan:
  - put: version
    params:
      bump: minor

- name: create-major
  plan:
  - put: version
    params:
      bump: major

- name: package-tile-generator
  plan:
  - aggregate:
    - get: base-pipeline-docker-image
      passed: [ create-dev ]
      trigger: true
    - get: tile-generator-repo
      passed: [ create-dev ]
      trigger: true
    - get: version
      trigger: true
  - task: build-package
    image: base-pipeline-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-repo
      outputs:
      - name: tile-generator-dist
      run:
        path: sh
        args:
        - -c 
        - python setup.py sdist && cp dist/tile_generator-*.tar.gz ../tile-generator-dist
        dir: tile-generator-repo
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Tile Generator package build failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator
  - put: tile-generator-package
    params:
      file: tile-generator-dist/tile_generator-*.tar.gz

- name: install-tile-generator
  plan:
  - aggregate:
    - get: base-pipeline-docker-image
      trigger: true
    - get: tile-generator-package
      passed: [ package-tile-generator ]
      trigger: true
    - get: tile-generator-repo
      passed: [ package-tile-generator ]
      trigger: true
    - get: version
      passed: [ package-tile-generator ]
      trigger: true
    - get: tile-generator-dockerfile-repo
      trigger: true
  - task: prepare-docker-build
    image: base-pipeline-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-dockerfile-repo
      - name: tile-generator-package
      outputs:
      - name: docker-build-dir
      run:
        path: sh
        args:
        - -c
        - cp tile-generator-package/* docker-build-dir/ && cp tile-generator-dockerfile-repo/ci/docker-tile-generator/* docker-build-dir/
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Tile Generator docker build failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator
  - put: tile-generator-docker-image
    params:
      build: docker-build-dir

- name: build-tile
  plan:
  - aggregate:
    - get: tile-generator-docker-image
      passed: [ install-tile-generator ]
      trigger: true
    - get: redis-boshrelease
    - get: tile-history
      trigger: false
    - get: tile-generator-repo
      passed: [ install-tile-generator ]
      trigger: true
    - get: version
      passed: [ install-tile-generator ]
      trigger: true
  - task: build-sample-apps
    image: tile-generator-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-repo
      - name: redis-boshrelease
      outputs:
      - name: sample-tile-build
      run:
        path: sh
        args:
        - -c
        - cp redis-boshrelease/redis-*.tgz tile-generator-repo/sample/resources/ && tile-generator-repo/sample/src/build.sh sample-tile-build
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Sample app build failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator
  - put: app-docker-image
    params:
      build: sample-tile-build/src
  - get: app-docker-image
    params:
      save: true
  - task: populate-docker-cache
    image: tile-generator-docker-image
    config:
      platform: linux
      inputs:
      - name: app-docker-image
      outputs:
      - name: docker-cache
      run:
        path: sh
        args: [ "-c", 'cp app-docker-image/image docker-cache/guidowb-sample-cf-app.tgz']
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Sample app docker build failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator
  - task: build-sample-tile
    image: tile-generator-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-repo
      - name: sample-tile-build
      - name: tile-history
      - name: docker-cache
      outputs:
      - name: generated-tile
      run:
        path: tile-generator-repo/ci/scripts/tile-build.sh
        args: [ "sample-tile-build", "tile-history", "generated-tile", "docker-cache" ]
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Tile build failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator
  - put: tile-history
    params:
      file: generated-tile/tile-history-*.yml
  - put: generated-tile
    params:
      file: generated-tile/*.pivotal

- name: acceptance-tests
  plan:
  - aggregate:
    - get: tile-generator-docker-image
      passed: [ build-tile ]
      trigger: true
    - get: tile-generator-tests
      trigger: true
    - get: generated-tile
      passed: [ build-tile ]
      trigger: true
    - get: tile-generator-repo
      passed: [ build-tile ]
      trigger: true
    - get: version
      passed: [ build-tile ]
      trigger: true
  - task: run-acceptance-tests
    image: tile-generator-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-tests
      - name: generated-tile
      run:
        path: tile-generator-tests/ci/scripts/run-acceptancetests.sh
        args: [ "generated-tile" ]
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Acceptance tests failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: claim-pcf
  plan:
  - aggregate:
    - get: tile-generator-docker-image
      passed: [ acceptance-tests ]
      trigger: true
    - get: tile-generator-tests
      passed: [ acceptance-tests ]
      trigger: true
    - get: generated-tile
      passed: [ acceptance-tests ]
      trigger: true
    - get: tile-generator-repo
      passed: [ acceptance-tests ]
      trigger: true
    - get: version
      passed: [ acceptance-tests ]
      trigger: true
    - put: pcf-environment
      params:
        acquire: true

- name: deploy-tile
  plan:
  - aggregate:
    - get: tile-generator-docker-image
      passed: [ claim-pcf ]
      trigger: true
    - get: tile-generator-tests
      passed: [ claim-pcf ]
      trigger: true
    - get: generated-tile
      passed: [ claim-pcf ]
      trigger: true
    - get: pcf-environment
      passed: [ claim-pcf ]
    - get: tile-generator-repo
      passed: [ claim-pcf ]
      trigger: true
    - get: version
      passed: [ claim-pcf ]
      trigger: true
  - task: run-deploy-tile
    image: tile-generator-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-tests
      - name: pcf-environment
      - name: generated-tile
      run:
        path: tile-generator-tests/ci/scripts/run-deploytile.sh
        args: [ "generated-tile", "pcf-environment" ]
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Deploy tile failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: deployment-tests
  plan:
  - aggregate:
    - get: tile-generator-docker-image
      passed: [ deploy-tile ]
      trigger: true
    - get: tile-generator-tests
      passed: [ deploy-tile ]
      trigger: true
    - get: generated-tile
      passed: [ deploy-tile ]
      trigger: true
    - get: pcf-environment
      passed: [ deploy-tile ]
    - get: tile-generator-repo
      passed: [ deploy-tile ]
      trigger: true
    - get: version
      passed: [ deploy-tile ]
      trigger: true
  - task: run-deployment-tests
    image: tile-generator-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-tests
      - name: pcf-environment
      - name: generated-tile
      run:
        path: tile-generator-tests/ci/scripts/run-deploymenttests.sh
        args: [ "generated-tile", "pcf-environment" ]
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Deployment tests failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: remove-tile
  plan:
  - aggregate:
    - get: tile-generator-docker-image
      passed: [ deployment-tests ]
      trigger: true
    - get: tile-generator-tests
      passed: [ deployment-tests ]
      trigger: true
    - get: generated-tile
      passed: [ deployment-tests ]
      trigger: true
    - get: pcf-environment
      passed: [ deployment-tests ]
    - get: tile-generator-repo
      passed: [ deployment-tests ]
      trigger: true
    - get: version
      passed: [ deployment-tests ]
      trigger: true
  - task: remove-tile
    image: tile-generator-docker-image
    config:
      platform: linux
      inputs:
      - name: tile-generator-tests
      - name: pcf-environment
      - name: generated-tile
      run:
        path: tile-generator-tests/ci/scripts/run-removetile.sh
        args: [ "generated-tile", "pcf-environment" ]
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Remove tile failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: release-pcf
  plan:
  - aggregate:
    - get: pcf-environment
      passed: [ remove-tile ]
      trigger: true
    - get: tile-generator-repo
      passed: [ remove-tile ]
      trigger: true
    - get: version
      passed: [ remove-tile ]
      trigger: true
  - put: pcf-environment
    params:
      release: pcf-environment
