---

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:

- name: tile-generator-repo
  type: git
  source:
    branch: master
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: dockerfile-repo
  type: git
  source:
    paths: [ "ci/Dockerfile", "ci/requirements.txt" ]
    branch: master
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: generated-tile
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: .*-(?P<version>.*)\.pivotal
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: tile-history
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: tile\-history-(?P<version>.*)\.yml
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: ci-docker-image
  type: docker-image
  source:
    repository: guidowb/tile-pipeline
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: app-docker-image
  type: docker-image
  source:
    repository: guidowb/sample-cf-app
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: pcf-environment
  type: pool
  source:
    uri: git@github.com:cf-platform-eng/pipeline-resource-pool
    branch: master
    pool: pcf
    private_key: {{github-pool-private-key}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-hook}}

jobs:

- name: build-docker
  plan:
  - get: dockerfile-repo
    trigger: true
  - put: ci-docker-image
    params:
      build: dockerfile-repo/ci

- name: unit-tests
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ build-docker ]
      trigger: true
    - get: tile-generator-repo
      trigger: true
  - task: run-unit-tests
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: tile-generator-repo
      run:
        path: tile-generator-repo/ci/scripts/run-unittests.sh
        args: [ "tile-generator-repo/lib" ]
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Unit tests failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: build-tile
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ unit-tests ]
      trigger: true
    - get: tile-generator-repo
      passed: [ unit-tests ]
      trigger: true
    - get: tile-history
      trigger: false
  - task: build-sample-apps
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: tile-generator-repo
      outputs:
      - name: sample-tile-build
      run:
        path: tile-generator-repo/sample/src/build.sh
        args: [ "sample-tile-build" ]
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Sample app build failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator
  - put: app-docker-image
    params:
      build: sample-tile-build/src
  - get: app-docker-image
    params:
      save: true
  - task: populate-docker-cache
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: app-docker-image
      outputs:
      - name: docker-cache
      run:
        path: sh
        args: [ "-c", 'cp app-docker-image/image docker-cache/guidowb-sample-cf-app.tgz']
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Sample app docker build failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator
  - task: build-sample-tile
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: tile-generator-repo
      - name: sample-tile-build
      - name: tile-history
      - name: docker-cache
      outputs:
      - name: generated-tile
      run:
        path: tile-generator-repo/ci/scripts/tile-build.sh
        args: [ "sample-tile-build", "tile-history", "generated-tile", "docker-cache" ]
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Tile build failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator
  - put: tile-history
    params:
      file: generated-tile/tile-history-*.yml
  - put: generated-tile
    params:
      file: generated-tile/*.pivotal

- name: acceptance-tests
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ build-tile ]
      trigger: true
    - get: tile-generator-repo
      passed: [ build-tile ]
      trigger: true
    - get: generated-tile
      passed: [ build-tile ]
      trigger: true
  - task: run-acceptance-tests
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: tile-generator-repo
      - name: generated-tile
      run:
        path: tile-generator-repo/ci/scripts/run-acceptancetests.sh
        args: [ "generated-tile" ]
    on_failure:
      aggregate:
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Acceptance tests failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: claim-pcf
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ acceptance-tests ]
      trigger: true
    - get: tile-generator-repo
      passed: [ acceptance-tests ]
      trigger: true
    - get: generated-tile
      passed: [ acceptance-tests ]
      trigger: true
    - put: pcf-environment
      params:
        acquire: true

- name: deploy-tile
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ claim-pcf ]
      trigger: true
    - get: tile-generator-repo
      passed: [ claim-pcf ]
      trigger: true
    - get: generated-tile
      passed: [ claim-pcf ]
      trigger: true
    - get: pcf-environment
      passed: [ claim-pcf ]
  - task: run-deploy-tile
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: tile-generator-repo
      - name: pcf-environment
      - name: generated-tile
      run:
        path: tile-generator-repo/ci/scripts/run-deploytile.sh
        args: [ "generated-tile", "pcf-environment" ]
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Deploy tile failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: deployment-tests
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ deploy-tile ]
      trigger: true
    - get: tile-generator-repo
      passed: [ deploy-tile ]
      trigger: true
    - get: generated-tile
      passed: [ deploy-tile ]
      trigger: true
    - get: pcf-environment
      passed: [ deploy-tile ]
  - task: run-deployment-tests
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: tile-generator-repo
      - name: pcf-environment
      - name: generated-tile
      run:
        path: tile-generator-repo/ci/scripts/run-deploymenttests.sh
        args: [ "generated-tile", "pcf-environment" ]
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Deployment tests failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: remove-tile
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ deployment-tests ]
      trigger: true
    - get: tile-generator-repo
      passed: [ deployment-tests ]
      trigger: true
    - get: generated-tile
      passed: [ deployment-tests ]
      trigger: true
    - get: pcf-environment
      passed: [ deployment-tests ]
  - task: remove-tile
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: tile-generator-repo
      - name: pcf-environment
      - name: generated-tile
      run:
        path: tile-generator-repo/ci/scripts/run-removetile.sh
        args: [ "generated-tile", "pcf-environment" ]
    on_failure:
      aggregate:
      - put: pcf-environment
        params:
          release: pcf-environment
      - put: slack-alert
        params:
          channel: {{slack-channel}}
          icon_emoji: ':concourse:'
          text: '(master) Remove tile failed, check <https://ci.run-01.haas-26.pez.pivotal.io/pipelines/tile-generator|here> for details'
          username: Tile Generator

- name: release-pcf
  plan:
  - get: pcf-environment
    passed: [ remove-tile ]
    trigger: true
  - put: pcf-environment
    params:
      release: pcf-environment
