---

resources:

- name: git-tile-generator-ci-repo
  type: git
  source:
    branch: pipeline
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: git-tile-generator-repo
  type: git
  source:
    branch: pipeline
    uri: http://github.com/cf-platform-eng/tile-generator.git

- name: generated-tile
  type: s3
  source:
    bucket: {{s3-bucket}}
    regexp: git-tile-generator-repo/sample/product/*.pivotal
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: base-ci-docker-image
  type: docker-image
  source:
    repository: guidowb/tile-pipeline
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:

- name: build-ci-docker-image
  plan:
  - get: git-tile-generator-ci-repo
    trigger: true
  - put: base-ci-docker-image
    params:
      build: git-tile-generator-ci-repo/ci

- name: build-sample-tile
  plan:
  - aggregate:
    - get: base-ci-docker-image
      trigger: true
    - get: git-tile-generator-repo
      trigger: true
  - task: build-sample-tile
    config:
      platform: linux
      image: "docker:///guidowb/tile-pipeline"
      inputs:
      - name: git-tile-generator-repo
      run:
        path: git-tile-generator-repo/ci/scripts/tile-build.sh
        args: [ "git-tile-generator-repo/sample" ]
 #       path: git-tile-generator-repo/ci/scripts/tile-build.sh
 #       args: ["git-tile-generator-repo/sample"]

